name: What drives me
favicon: null
layout_spectrum: 0.99629
typography_spectrum: 0.6338802790269256
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7e0000'
    - '#c7b47b'
    - '#4c3d28'
    - '#b26b33'
    - '#fefefe'
  brandStrength: 1
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
