name: What drives me
favicon: null
layout_spectrum: 0.99629
typography_spectrum: 0.00371
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#e0ebf0'
    - '#b9bab7'
    - '#bd5a67'
    - '#292a30'
  brandStrength: 0.5
  lightness: 0
  saturation: 0
  rhythmicContrast: 1
purpose: []
